name: Remote SSH Command
on:
  push
#   pull_request:
#     types:
#       - closed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT}}
          script: |
            if [ ! -f published.lock ]; then
              ./publish.sh
              echo "$(date)" > published.lock
            else
              echo "Script already executed. Skipping script execution."
            fi
