name: Remote SSH Command
on:
  push
#   pull_request:
#     types:
#       - closed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: users.cs.umb.edu:22
          username: shivangr
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
